"""Project-wide constants and file locations."""

from pathlib import Path

from .units import KELVIN_OFFSET, cm_to_m

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ATTACHMENT_DIR = PROJECT_ROOT / "附件"
RESULT_TEMPLATE_DIR = ATTACHMENT_DIR / "附件3"
ATTACHMENT_1_PATH = ATTACHMENT_DIR / "附件1.xlsx"
ATTACHMENT_2_PATH = ATTACHMENT_DIR / "附件2.xlsx"

CELSIUS_TO_KELVIN = KELVIN_OFFSET

CYLINDER_LENGTH_M = 0.25
CYLINDER_RADIUS_CM = 2.0
CYLINDER_RADIUS_M = cm_to_m(CYLINDER_RADIUS_CM)
INITIAL_TEMPERATURE_C = 28.0
INITIAL_MOISTURE_DRY_BASIS = 2.55

Q1_DENSITY_KG_M3 = 820.0
Q1_HEAT_CAPACITY_J_KG_K = 2600.0
Q1_THERMAL_CONDUCTIVITY_W_M_K = 0.36
Q1_CONVECTION_H_W_M2_K = 25.0
Q1_CONVECTION_HM_M_S = 8e-7
Q1_DIFFUSIVITY_PREFACTOR_M2_S = 7e-9
Q1_DIFFUSIVITY_EXPONENT = 0.89

DEFAULT_RADIAL_STEP_M = 0.001
Q1_TIME_STEP_S = 1.0
Q1_END_TIME_S = 1800.0
Q2_END_TIME_S = 10800.0
Q3_TIME_STEP_S = 60.0
Q3_TARGET_MOISTURE = 0.15

PICARD_TOLERANCE = 1e-8
PICARD_MAX_ITERATIONS = 30
